name: Deploy to Amazon ECS

on:
  push:
     branches: [main]
jobs:
  deploy-SFTP:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        
      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
            node-version: '16'
      
      - name: Install npm dependencies
        run: npm install
        
      - name: 🔨 Build Project
        env:
          REACT_APP_OPENWEATHER_KEY: ${{ secrets.REACT_APP_OPENWEATHER_KEY }}
          REACT_APP_OPENWEATHER_URL: ${{ secrets.REACT_APP_OPENWEATHER_URL }}
        run: npm run build
        
      - name: 📂 Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USER_AWS_DEPLOYER }}
          server: ${{ secrets.HOST_AWS_DEPLOY }}
          ssh_private_key: ${{ secrets.PRUEBA_KEY_AWS }} 
          local_path: './build/*'
          remote_path: '/home/${{ secrets.USER_AWS_DEPLOYER }}/${{ secrets.DIRECTORY_DEPLOY }}'
          args: '-o ConnectTimeout=5'
