name: Deploy to Amazon ECS

on:
  push:
     branches: [main]
jobs:
  deploy-SFTP:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        
      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
            node-version: '16'
      
      - name: Install npm dependencies
        run: npm install
        
      - name: 🔨 Build Project
        env:
          REACT_APP_OPENWEATHER_KEY: ${{ secrets.REACT_APP_OPENWEATHER_KEY }}
          REACT_APP_OPENWEATHER_URL: ${{ secrets.REACT_APP_OPENWEATHER_URL }}
        run: npm run build
        
      - name: 📂 Deploy to Server
        env:
            PRIVATE_KEY: ${{ secrets.PRUEBA_KEY_AWS }}
            SOURCE: './build/*'
            HOST: ${{ secrets.HOST_AWS_DEPLOY }}
            USER: ${{ secrets.USER_AWS_DEPLOYER }}
            REMOTE_PATH: ${{ secrets.DIRECTORY_DEPLOY }}
            EXCLUDE: '/dist/, /node_modules/'
        run: |
          echo "Desplegando a $HOST en directorio $REMOTE_PATH"
          rsync -avzh --delete -e 'ssh -i $PRIVATE_KEY' --progress $SOURCE $USER@$HOST:/home/$USER/$REMOTE_PATH
